"""Add 'updated' field to mods

Revision ID: 4a4cb968a56
Revises: 59abfc7b45d
Create Date: 2014-06-10 02:46:33.333580

"""

# revision identifiers, used by Alembic.
revision = '4a4cb968a56'
down_revision = '59abfc7b45d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated')
    ### end Alembic commands ###
