"""change user profiles

Revision ID: f4c441491815
Revises: 6ffd5dd5efab
Create Date: 2016-04-19 07:38:18.435995

"""

# revision identifiers, used by Alembic.
revision = 'f4c441491815'
down_revision = '6ffd5dd5efab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameversion', sa.Column('is_beta', sa.Boolean(), nullable=True))
    op.add_column('mod', sa.Column('rating_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('mod', sa.Column('total_score', sa.Float(), nullable=True))
    op.add_column('modversion', sa.Column('is_beta', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('facebookUsername', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('showCreated', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('showEmail', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('showFacebookName', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('showForumName', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('showIRCName', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('showLocation', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('showRedditName', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('showTwitchName', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('showTwitterName', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('showYoutubeName', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('twitchUsername', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('youtubeUsername', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'youtubeUsername')
    op.drop_column('user', 'twitchUsername')
    op.drop_column('user', 'showYoutubeName')
    op.drop_column('user', 'showTwitterName')
    op.drop_column('user', 'showTwitchName')
    op.drop_column('user', 'showRedditName')
    op.drop_column('user', 'showLocation')
    op.drop_column('user', 'showIRCName')
    op.drop_column('user', 'showForumName')
    op.drop_column('user', 'showFacebookName')
    op.drop_column('user', 'showEmail')
    op.drop_column('user', 'showCreated')
    op.drop_column('user', 'facebookUsername')
    op.drop_column('modversion', 'is_beta')
    op.drop_column('mod', 'total_score')
    op.drop_column('mod', 'rating_count')
    op.drop_column('gameversion', 'is_beta')
    ### end Alembic commands ###
